version: '3.8'
services:
  nifi:
    image: apache/nifi:1.26.0
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - shared:/data
  spark:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - shared:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
volumes:
  shared:
