services:
  spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_OPTS=--packages io.delta:delta-spark_2.12:3.2.0
    command: start-notebook.sh --NotebookApp.token=''
